// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FullScreenBannerCarouselCard: typeof import('./src/components/full-screen-banner/carousel-card.vue')['default']
    FullScreenBannerFullBanner: typeof import('./src/components/full-screen-banner/full-banner.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavigationSearchPageBar: typeof import('./src/components/navigation/search-page-bar.vue')['default']
    NavigationTopbar: typeof import('./src/components/navigation/top-bar.vue')['default']
    NavigationTopBar: typeof import('./src/components/navigation/top-bar.vue')['default']
    SharedUiAlliedImage: typeof import('./src/components/shared-ui/allied-image.vue')['default']
    SharedUiCarousel: typeof import('./src/components/shared-ui/carousel.vue')['default']
    SharedUiCarouselCard: typeof import('./src/components/shared-ui/carousel-card.vue')['default']
    SharedUiFooter: typeof import('./src/components/shared-ui/footer.vue')['default']
    SharedUiGithubLink: typeof import('./src/components/shared-ui/github-link.vue')['default']
    SharedUiHambuger: typeof import('./src/components/shared-ui/hambuger.vue')['default']
    SharedUiHambugerBtn: typeof import('./src/components/shared-ui/hambuger-btn.vue')['default']
    SharedUiMenuButton: typeof import('./src/components/shared-ui/menu-button.vue')['default']
    SharedUiScrollMenu: typeof import('./src/components/shared-ui/scroll-menu.vue')['default']
    SharedUiSocialconnect: typeof import('./src/components/shared-ui/socialconnect.vue')['default']
    SharedUiSocialConnect: typeof import('./src/components/shared-ui/social-connect.vue')['default']
    SharedUiTwitter: typeof import('./src/components/shared-ui/twitter.vue')['default']
    SocialLinksFacebookBtn: typeof import('./src/components/social-links/facebook-btn.vue')['default']
    SocialLinksInstagramBtn: typeof import('./src/components/social-links/instagram-btn.vue')['default']
    SocialLinksPlatformsBtn: typeof import('./src/components/social-links/platforms-btn.vue')['default']
    SocialLinksTwitter: typeof import('./src/components/social-links/twitter.vue')['default']
    SocialLinksTwitterBtn: typeof import('./src/components/social-links/twitter-btn.vue')['default']
    TrendsDisplayFourColumnDisplay: typeof import('./src/components/trends-display/four-column-display.vue')['default']
    TrendsDisplayTwoColumnDisplay: typeof import('./src/components/trends-display/two-column-display.vue')['default']
  }
}

export { }
